# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='url',
            field=models.CharField(default=0, max_length=128, verbose_name='权限路由'),
            preserve_default=False,
        ),
    ]
