# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-26 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='swiped',
            unique_together=set([('uid', 'sid')]),
        ),
    ]
