# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-24 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenum', models.CharField(max_length=20, verbose_name='手机号')),
                ('nickname', models.CharField(max_length=128, verbose_name='昵称')),
                ('sex', models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=16, verbose_name='性别')),
                ('birth_year', models.CharField(max_length=64, verbose_name='出生年')),
                ('birth_month', models.CharField(max_length=64, verbose_name='出生月')),
                ('birth_day', models.CharField(max_length=64, verbose_name='出生日')),
                ('avatar', models.CharField(max_length=255, verbose_name='个人形象')),
                ('location', models.CharField(max_length=255, verbose_name='常居地')),
            ],
        ),
    ]
