# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-25 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dating_sex',
            field=models.CharField(choices=[(0, 'male'), (1, 'female')], max_length=16, null=True, verbose_name='匹配的性别'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=255, null=True, verbose_name='目标城市'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_dating_age',
            field=models.CharField(max_length=50, null=True, verbose_name='最大交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_distance',
            field=models.CharField(max_length=50, null=True, verbose_name='最大查找范围'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_dating_age',
            field=models.CharField(max_length=18, null=True, verbose_name='最小交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_distance',
            field=models.CharField(max_length=1, null=True, verbose_name='最小查找范围'),
        ),
    ]
