# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-25 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190625_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_dating_age',
            field=models.IntegerField(max_length=50, null=True, verbose_name='最大交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_distance',
            field=models.IntegerField(max_length=50, null=True, verbose_name='最大查找范围'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_dating_age',
            field=models.IntegerField(max_length=18, null=True, verbose_name='最小交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_distance',
            field=models.IntegerField(max_length=1, null=True, verbose_name='最小查找范围'),
        ),
    ]
