# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-25 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190625_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auto_play',
            field=models.NullBooleanField(default=False, verbose_name='自动播放视频'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_dating_age',
            field=models.IntegerField(default=50, null=True, verbose_name='最大交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_distance',
            field=models.IntegerField(default=50, null=True, verbose_name='最大查找范围'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_dating_age',
            field=models.IntegerField(default=18, null=True, verbose_name='最小交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_distance',
            field=models.IntegerField(default=1, null=True, verbose_name='最小查找范围'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='only_matche',
            field=models.NullBooleanField(default=False, verbose_name='不让为匹配的人看我的相册'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vibration',
            field=models.NullBooleanField(default=False, verbose_name='开启震动'),
        ),
    ]
