# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190625_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='vip_id',
            field=models.IntegerField(default=0, verbose_name='会员id'),
        ),
    ]
