# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_profile_vip_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='vip_id',
        ),
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=0, verbose_name='会员id'),
        ),
    ]
